### ISSUE TITLE
v3.4

### ISSUE THREAD

**Issue by kachkaev** [Dattaya/react-boilerplate-object#2]
Given that this fork is mentioned in https://github.com/mxstbr/react-boilerplate/issues/936, I thought it'd be useful to upgrade it to `react-boilerplate@3.4`. Quite a few people in the community may appreciate it!

**Comment by Dattaya** [comment]
It's done, though I made a mistake and squashed everything together (and did a push to GH) 😳 so I had to merge it again with 'ours' strategy and now it's a bit of a mess, sorry. Please let me know if you experience any issues with 3.4.
